//
// Created by 温和 on 2018/10/1.
//
#pragma once
#ifndef POKEMON_CONST_DEFINE_H
#define POKEMON_CONST_DEFINE_H

#define TRUE 1
#define FALSE 0

enum Type {
    attacker,
    tanker,
    defender,
    assassin
};

#define ATTACKER_INIT_HP 10
#define ATTACKER_INIT_STRENGTH 5
#define ATTACKER_INIT_DEFNESE 2
#define ATTACKER_INIT_ATTACK_INTERVAL 1.0

#define ATTACKER_GROW_HP 10
#define ATTACKER_GROW_STRENGTH 5
#define ATTACKER_GROW_DEFNESE 2
#define ATTACKER_GROW_ATTACK_INTERVAL 1.0

#define TANKER_INIT_HP 10
#define TANKER_INIT_STRENGTH 5
#define TANKER_INIT_DEFNESE 2
#define TANKER_INIT_ATTACK_INTERVAL 1.0

#define TANKER_GROW_HP 10
#define TANKER_GROW_STRENGTH 5
#define TANKER_GROW_DEFNESE 2
#define TANKER_GROW_ATTACK_INTERVAL 1.0

#define DEFENDER_INIT_HP 10
#define DEFENDER_INIT_STRENGTH 5
#define DEFENDER_INIT_DEFNESE 2
#define DEFENDER_INIT_ATTACK_INTERVAL 1.0

#define DEFENDER_GROW_HP 10
#define DEFENDER_GROW_STRENGTH 5
#define DEFENDER_GROW_DEFNESE 2
#define DEFENDER_GROW_ATTACK_INTERVAL 1.0

#define ASSASSIN_INIT_HP 10
#define ASSASSIN_INIT_STRENGTH 5
#define ASSASSIN_INIT_DEFNESE 2
#define ASSASSIN_INIT_ATTACK_INTERVAL 1.0

#define ASSASSIN_GROW_HP 10
#define ASSASSIN_GROW_STRENGTH 5
#define ASSASSIN_GROW_DEFNESE 2
#define ASSASSIN_GROW_ATTACK_INTERVAL 1.0


#define TEST_WIDTH 300
#define TEST_HEIGHT 600
#define LINE_WIDTH 80
#define LINE_HEIGHT 20
#define SIDE_INTERVAL 30
#define LINE_INTERVAL 10

#endif //POKEMON_CONST_DEFINE_H
